结构体实例


#include<iostream>
#include<string>
using namespace std;
#include<ctime>

//xx学生的结构体
struct Student
{
	//姓名
	string sName;
	//分数
	int score;


};

struct Teacher
{
	//姓名
	string  tName;
	//学生数组
	struct Student sArray[5];
};
//给老师和学生赋值
void allocatSpace(struct Teacher tArray[],int len)
{
	//给老师赋值
	string nameSeed = "ABCDE";
	for (int i = 0; i < len; i++)
	{

		tArray[i].tName = "teacher_";
		tArray[i].tName += nameSeed[i];

		//通过循环给每名老师所带的学生赋值
		for (int j = 0; j < 5; j++)
		{
			tArray[i].sArray[j].sName = "Student_";
			tArray[i].sArray[j].sName += nameSeed[j];

			int random = rand()%61+40;// 60:40~99

			tArray[i].sArray[j].score =random;

		}
	}
}
//打印所以信息
void printInfo(struct Teacher tArray[], int len)
{
	for (int i = 0; i < len; i++)
	{
		cout << "老师姓名：" << tArray[i].tName << endl;
		for (int j = 0; j < 5; j++)
		{

			cout << "\t学生姓名：" << tArray[i].sArray[j].sName
				<< "考试分数： " << tArray->sArray[j].score << endl;
		}
			
	}

}
int main()
{
	//随机数种子
	srand((unsigned int)time(NULL));


	//1.创建3名老师的数组
	struct Teacher tArray[3];
	
	//2.通过函数给3名老师的信息赋值，并通过老师带的学生信息赋值
	int len = sizeof(tArray) / sizeof(tArray[0]);
	allocatSpace(tArray, len);

	//打印所以老师和学生信息
	printInfo(tArray,len);

	system("pause");
	return 0;
}


结构体实例

#include<iostream>
#include<string>
using namespace std;

//设计英雄结构体
struct  Hero
{
	//姓名
	string name;
	//年龄
	int age;
	// 性别
	string sex;
};
//排序
void bubbleSort(struct Hero heroArray[], int len)
{
	for (int i = 0; i < len - 1; i++)
	{
		for (int j = 0; j < len - i - 1; j++)
		{

			//如果j下标的元素年龄大于j+1下标 元素交换
			if (heroArray[j].age > heroArray[j + 1].age)
			{
				struct Hero temp = heroArray[j];
				heroArray[j] = heroArray[j + 1];
				heroArray[j + 1] = temp;
			}
		}
	}


}
//打印排序后的信息
void printHero(struct Hero heroArray[], int len)
{
	for (int i = 0; i < len; i++)
	{
		cout << "姓名：" << heroArray[i].name << "年龄：" << heroArray[i].age
			<< "性别：" << heroArray[i].sex << endl;
	}
}

int main()
{
	struct Hero heroArray[5] =
	{
	{"刘备",23,"男"},
	{"关羽",22,"男"},
	{ "张飞",20,"男" },
	{"赵云",21,"男"},
	{ "貂蝉",19,"女"},
	};
int len =sizeof(heroArray) / sizeof(heroArray[0]);
	/*for (int i = 0; i < len; i++)
	{
		cout << "姓名：" << heroArray[i].name << "年龄：" << heroArray[i].age
			<< "性别：" << heroArray[i].sex << endl;
	}*/
	//3.对数组进行排序，按照年龄进行升序排列 
	bubbleSort(heroArray, len);

	//4.打印输出
	printHero(heroArray, len);
	system("pause");
	return 0;
}
